create an email var
DeborahAlmeida/pokebattle pull request #10
Opened 2021-06-17 12:25 UTC by DeborahAlmeida

## Objective and Motivation
- Create an email var to manage the sending of emails

2021-06-17 13:55 UTC, fjsj commented on backend/pokebattle/settings/production.py
> +EMAIL = config("EMAIL")
I would change to `FROM_EMAIL`

2021-06-17 13:55 UTC, fjsj requested changes
Please check comments

2021-06-17 16:18 UTC, DeborahAlmeida commented on backend/pokebattle/settings/production.py
> +EMAIL = config("EMAIL")
Thank you!

2021-06-18 13:44 UTC, rsarai approved these changes

2021-06-18 18:08 UTC, merged