send email to opponent when create a battle
DeborahAlmeida/pokebattle pull request #16
Opened 2021-06-25 13:35 UTC by DeborahAlmeida

## Objective and Motivation
- As a selected opponent I receive an email when I'm invited to a match

2021-06-25 14:24 UTC, fjsj commented on backend/battle/battles/email.py
> +        recipient_list=[opponent],
Should be `opponent.email` here.
This is only working right now because your `__str__` is `self.email`. You shouldn't rely on that.

2021-06-25 14:25 UTC, fjsj requested changes
Please check comments

2021-06-25 15:35 UTC, DeborahAlmeida commented on backend/battle/battles/email.py
> +        recipient_list=[opponent],
Oh, you told me once and I forgot to apply, thanks to remember me!

2021-06-29 14:53 UTC, fjsj approved these changes
LGTM, thanks

2021-06-29 14:54 UTC, merged