use redux to render user and battle detail
DeborahAlmeida/pokebattle pull request #39
Opened 2021-08-24 01:25 UTC by DeborahAlmeida

2021-08-26 14:40 UTC, rsarai requested changes
minor comments, everything looking good overall :rocket:

2021-08-26 14:40 UTC, rsarai commented on frontend/js/reducers/index.js
> +  battleState: battleReducer,
Let's make the name simple here, since this will be the name on your store, please use it `battle` and `user`

2021-08-26 14:40 UTC, rsarai commented on frontend/js/actions/setBattle.js
> +import { getTeamData } from 'utils/api';
I liked the organization here :star:

2021-08-26 14:40 UTC, rsarai commented on frontend/js/store/index.js
> +export const Store = createStore(Reducers, applyMiddleware(thunk));
A small comment here, the store and reducers should all start with lowercase.

2021-08-26 14:40 UTC, rsarai commented on frontend/js/reducers/userReducer.js
> +export const userReducer = (state = { user: null }, action) => {
this initialState shouldn't be something general with all the required data?

2021-08-26 14:40 UTC, rsarai commented on frontend/js/reducers/battleReducer.js
> +export const battleReducer = (state = initialState, action) => {
same here, this initialState shouldn't be more complete? Like having the user and battle and all other required attributes

2021-08-26 18:08 UTC, DeborahAlmeida commented on frontend/js/reducers/index.js
> +  battleState: battleReducer,
great!

2021-08-26 18:08 UTC, DeborahAlmeida commented on frontend/js/actions/setBattle.js
> +import { getTeamData } from 'utils/api';
Thanks :dancers:

2021-08-26 18:14 UTC, DeborahAlmeida commented on frontend/js/store/index.js
> +export const Store = createStore(Reducers, applyMiddleware(thunk));
great! I will fix that, thanks!

2021-08-27 14:03 UTC, rsarai approved these changes

2021-08-27 18:12 UTC, merged