Feature/react battle list
DeborahAlmeida/pokebattle pull request #40
Opened 2021-08-24 22:24 UTC by DeborahAlmeida

2021-08-26 15:03 UTC, rsarai requested changes

2021-08-26 15:03 UTC, rsarai commented on backend/templates/spa/spa_template.html
> +        <a class ="anchor_user" href="{% url 'spa_template_list' %}">
this namespace can be improved :eyes:

2021-08-26 15:03 UTC, rsarai commented on frontend/js/App.js
> +        <Route component={BattleList} path={Urls.spa_template_list()} />
same here

2021-08-26 15:03 UTC, rsarai commented on frontend/js/actions/setBattle.js
> +import { getTeamData } from 'utils/api';
let's define a pattern here, to use `set` or `get`

2021-08-26 15:03 UTC, rsarai commented on frontend/js/actions/setBattle.js
> +function fetchBattle(battle) {
this is the battle or the battle id? If it's the battle id let's make it clear

2021-08-26 15:03 UTC, rsarai commented on frontend/js/actions/getBattleList.js
> +import { getBattles } from 'utils/api';
the name of this action is different out of the pattern here, let's define a pattern or set or get

2021-08-26 15:03 UTC, rsarai commented on frontend/js/actions/getBattleList.js
> +function fetchBattleList() {
The same goes for the function names on all actions

2021-08-26 15:03 UTC, rsarai commented on frontend/js/pages/BattleList.js
> +    props.setCurrentUser();
What happens if the user already is saved on the store?

2021-08-26 15:03 UTC, rsarai commented on frontend/js/reducers/index.js
> +  battleListState: battleListReducer,
please, rename this to `battles`

2021-08-26 15:03 UTC, rsarai commented on frontend/js/reducers/battleReducer.js
> +import { BATTLE_DETAIL } from '../constants';
I already reviewed this and some other parts of this PR, did you have any branch issues?

2021-08-26 15:03 UTC, rsarai commented on frontend/js/reducers/battleListReducer.js
> +export const battleListReducer = (state = {}, action) => {
A note, you can have a single reducer for battle that deals with multiple actions. Please move this to the `battleReducer.js`

2021-08-26 19:34 UTC, DeborahAlmeida commented on backend/templates/spa/spa_template.html
> +        <a class ="anchor_user" href="{% url 'spa_template_list' %}">
thanks!

2021-08-26 19:36 UTC, DeborahAlmeida commented on frontend/js/actions/setBattle.js
> +import { getTeamData } from 'utils/api';
great!

2021-08-26 19:37 UTC, DeborahAlmeida commented on frontend/js/actions/setBattle.js
> +function fetchBattle(battle) {
I will change this to battleId, thanks!

2021-08-26 19:38 UTC, DeborahAlmeida commented on frontend/js/actions/getBattleList.js
> +import { getBattles } from 'utils/api';
okay!

2021-08-26 19:41 UTC, DeborahAlmeida commented on frontend/js/actions/getBattleList.js
> +function fetchBattleList() {
Alright :dancers:

2021-08-26 19:41 UTC, DeborahAlmeida commented on frontend/js/pages/BattleList.js
> +    props.setCurrentUser();
I will create a conditional to just make API request if the user is still null

2021-08-26 19:42 UTC, DeborahAlmeida commented on frontend/js/reducers/index.js
> +  battleListState: battleListReducer,
great!

2021-08-26 19:43 UTC, DeborahAlmeida commented on frontend/js/reducers/battleReducer.js
> +import { BATTLE_DETAIL } from '../constants';
I didn't, I guess

2021-08-26 19:49 UTC, DeborahAlmeida commented on frontend/js/reducers/battleListReducer.js
> +export const battleListReducer = (state = {}, action) => {
great! Thanks :)

2021-08-27 14:28 UTC, rsarai approved these changes
requested one minor thing, but looks good overall

2021-08-27 14:28 UTC, rsarai commented on frontend/js/pages/BattleList.js
> +  const { user } = props;
You can deconstruct this is a single line:
```javascript
const { user, battles } = props;
```

2021-08-27 14:29 UTC, rsarai commented
There are some conflicts here, please fix them before merging the PR

2021-08-27 18:49 UTC, merged