add new models to battle's app
DeborahAlmeida/pokebattle pull request #5
Opened 2021-04-30 19:14 UTC by DeborahAlmeida

## Objective and Motivation
- Refactor the code
- Normalize the database

2021-04-30 19:23 UTC, DeborahAlmeida commented
Hey! When I did 'git push' and created the pull request, my models didn't appear here with the modifications. So, I commented on the file to Git identify it and show the code to be review :)

2021-05-03 12:55 UTC, rsarai requested changes
Also, the build is breaking on the prospector step please fix them :)

2021-05-03 12:55 UTC, rsarai commented on backend/battle/migrations/0001_initial.py
> -                ('id', models.AutoField(primary_key=True, serialize=False)),
This will break your migrations in the production environment. I suggest you keep old migrations untouched and create new ones

2021-05-03 12:55 UTC, rsarai commented on backend/battle/migrations/0002_delete_battle.py
> -class Migration(migrations.Migration):
If this was already deployed you should not delete the migration

2021-05-03 12:55 UTC, rsarai commented on backend/battle/models.py
> +    def publish(self):
Is this required for something?

2021-05-03 12:55 UTC, rsarai commented on backend/battle/models.py
> +    def publish(self):
Is this required?

2021-05-03 12:55 UTC, rsarai commented on backend/pokemon/migrations/0001_initial.py
> +# Generated by Django 3.2 on 2021-04-30 19:01
Any reason for this change?

2021-05-10 16:54 UTC, closed without merging